### ISSUE TITLE
Cannot invoke consumer twice

### ISSUE THREAD

**Issue by dajudge** [dajudge/kafkaproxy#10]
https://github.com/dajudge/kafkaproxy/commit/ea68a78f6420ddb76994b8e82d60da03e0bfa29e1 has an issue when two consumers are started consecutively.

Steps to reproduce:
1. Build a docker image from commit specified above and use it in `example/docker-compose.yaml`.
2. Run the following commands:
```
# Start the test setup
docker-compose -f example/docker-compose.yml up -d
# Create the test topic
docker run --rm --net host -i confluentinc/cp-zookeeper:5.2.1 kafka-topics --create --topic my-test-topic --bootstrap-server localhost:4000 --partitions 1 --replication-factor 1
# Produce to test topic
echo "Hello, kafkaproxy" | docker run --rm --net host -i confluentinc/cp-zookeeper:5.2.1 kafka-console-producer --broker-list localhost:4000 --topic my-test-topic
# Consume 1st time
docker run --rm --net host -it confluentinc/cp-zookeeper:5.2.1 kafka-console-consumer --bootstrap-server localhost:4000 --topic my-test-topic --from-beginning --max-messages 1
# Consume 2nd time
docker run --rm --net host -it confluentinc/cp-zookeeper:5.2.1 kafka-console-consumer --bootstrap-server localhost:4000 --topic my-test-topic --from-beginning --max-messages 1
# The last command fails with a stack trace
```

The log from the console of the last command is:
```
[2020-04-02 09:52:22,066] ERROR Error processing message, terminating consumer process:  (kafka.tools.ConsoleConsumer$)
org.apache.kafka.common.protocol.types.SchemaException: Error reading field 'api_versions': Error reading array of size 44, only 21 bytes available
        at org.apache.kafka.common.protocol.types.Schema.read(Schema.java:77)
        at org.apache.kafka.common.protocol.ApiKeys.parseResponse(ApiKeys.java:308)
        at org.apache.kafka.common.protocol.ApiKeys$1.parseResponse(ApiKeys.java:152)
        at org.apache.kafka.clients.NetworkClient.parseStructMaybeUpdateThrottleTimeMetrics(NetworkClient.java:687)
        at org.apache.kafka.clients.NetworkClient.handleCompletedReceives(NetworkClient.java:811)
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:544)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:265)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:236)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:215)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:235)
        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:317)
        at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1226)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1191)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1176)
        at kafka.tools.ConsoleConsumer$ConsumerWrapper.receive(ConsoleConsumer.scala:439)
        at kafka.tools.ConsoleConsumer$.process(ConsoleConsumer.scala:105)
        at kafka.tools.ConsoleConsumer$.run(ConsoleConsumer.scala:77)
        at kafka.tools.ConsoleConsumer$.main(ConsoleConsumer.scala:54)
        at kafka.tools.ConsoleConsumer.main(ConsoleConsumer.scala)
Processed a total of 0 messages

```

**Comment by dajudge** [comment]
Fixed with 4a790df
