### ISSUE TITLE
Support Kafka 2.8?

### ISSUE THREAD

**Issue by jhovell** [dajudge/kafkaproxy#31]
Trying to connect to a cluster running 2.8 I get the following error:

18:48:12 ERROR [co.da.pr.RelayingChannelInboundHandler] (nioEventLoopGroup-4-2) [78e9fbd6-a1ee-4bb6-b901-d9b8bfdfab99] Exception in upstream channel.: java.lang.IllegalArgumentException: Invalid version for API key METADATA: 11
	at org.apache.kafka.common.protocol.ApiKeys.schemaFor(ApiKeys.java:343)
	at org.apache.kafka.common.protocol.ApiKeys.responseSchema(ApiKeys.java:317)
	at org.apache.kafka.common.protocol.ApiKeys.parseResponse(ApiKeys.java:325)
	at com.dajudge.kafkaproxy.protocol.KafkaMessage.lambda$responseBody$2(KafkaMessage.java:90)
	at com.dajudge.kafkaproxy.protocol.KafkaMessage.withPayload(KafkaMessage.java:100)
	at com.dajudge.kafkaproxy.protocol.KafkaMessage.responseBody(KafkaMessage.java:87)
	at com.dajudge.kafkaproxy.protocol.rewrite.BaseReflectingRewriter.rewriteMessageBody(BaseReflectingRewriter.java:55)
	at com.dajudge.kafkaproxy.protocol.rewrite.BaseReflectingRewriter.rewriteMessage(BaseReflectingRewriter.java:49)
	at com.dajudge.kafkaproxy.protocol.rewrite.BaseReflectingRewriter.rewrite(BaseReflectingRewriter.java:41)
	at com.dajudge.kafkaproxy.protocol.rewrite.CompositeRewriter.rewrite(CompositeRewriter.java:40)
	at com.dajudge.kafkaproxy.protocol.KafkaRequestStore.process(KafkaRequestStore.java:66)
	at com.dajudge.kafkaproxy.protocol.RewritingKafkaMessageDuplexHandler.channelRead(RewritingKafkaMessageDuplexHandler.java:39)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at com.dajudge.kafkaproxy.protocol.DecodingKafkaMessageInboundHandler.onMessageComplete(DecodingKafkaMessageInboundHandler.java:26)
	at com.dajudge.kafkaproxy.protocol.DecodingKafkaMessageInboundHandler.onMessageComplete(DecodingKafkaMessageInboundHandler.java:23)
	at com.dajudge.proxybase.AbstractChunkedMessageStreamInboundHandler.lambda$channelRead$0(AbstractChunkedMessageStreamInboundHandler.java:33)
	at com.dajudge.proxybase.ChunkedMessageCollector.append(ChunkedMessageCollector.java:39)
	at com.dajudge.proxybase.AbstractChunkedMessageStreamInboundHandler.channelRead(AbstractChunkedMessageStreamInboundHandler.java:33)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at com.dajudge.proxybase.LoggingContextHandler.lambda$channelRead$0(LoggingContextHandler.java:40)
	at com.dajudge.proxybase.LogHelper.withChannelId(LogHelper.java:33)
	at com.dajudge.proxybase.LoggingContextHandler.channelRead(LoggingContextHandler.java:38)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)

Looking at a similar proxy seems like the issue might be lack of support for version 2.8 of Kafka.

https://github.com/grepplabs/kafka-proxy/commit/5c0fd2f970c53563677e1728df8ffb6de2dd9105

**Comment by dajudge** [comment]
Thanks for your report!

You are correct: this is most certainly due to the fact that kafkaproxy currently uses only v2.6.0 of the kafka client library. I'll see to make the necessary updates in the next 2-3 weeks and then release a new version of kafkaproxy w/ kafka 2.8 support.

**Comment by dajudge** [comment]
I created a new issue for the SSL configuration problem.
